name: build and deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ vars.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  IMAGE_TAG: ${{ github.run_number }}
  CONTAINER_IMAGE: "pocui-app"
  CONTAINER_REGISTRY_NAME: "acrpocterraform"
  CONTAINER_APP: "mycontainerapp"
  CONTAINERAPP_RESOURCEGROUP: "TerraformPoc-App"
  
jobs:
  CICD:
    name: Build and Deploy Application to Azure
    runs-on: ubuntu-latest
  
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure set subscription
      run: az account set --subscription ${{ vars.ARM_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Terraform

    - name: Build the Docker image
      run: docker build -t ${{ env.CONTAINER_IMAGE }} -f Dockerfile .
      working-directory: ./terraform-poc-ui

    - name: tag image
      run: docker tag ${{ env.CONTAINER_IMAGE }} ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{env.CONTAINER_IMAGE}}:${{ env.IMAGE_TAG }}
      
    - name: login to container registry
      run: az acr login --name ${{ env.CONTAINER_REGISTRY_NAME }}

    - name: push image to container registry
      run: docker push ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{env.CONTAINER_IMAGE}}:${{ env.IMAGE_TAG }}

    - name: Set registry in container app
      run: |
        az containerapp registry set \
          --name mycontainerapp \
          --resource-group TerraformPoc-App \
          --server acrpocterraform.azurecr.io \
          --identity $(az identity show --name container-app-identity --resource-group TerraformPoc-App --query id -o tsv)
      
    - name: Update Container App with new image
      run: |
        az containerapp update --name ${{ env.CONTAINER_APP }} \
          --resource-group ${{ env.CONTAINERAPP_RESOURCEGROUP }} \
          --image ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE }}:${{ env.IMAGE_TAG }} \
          --output table
